//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lcms2.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lcms2.res.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad dictionary Name/Value.
        /// </summary>
        internal static string bad_dictionary_name_value {
            get {
                return ResourceManager.GetString("bad_dictionary_name_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save floating point data, CLUT are 8 or 16 bit only.
        /// </summary>
        internal static string cannot_save_floating_point_clut {
            get {
                return ResourceManager.GetString("cannot_save_floating_point_clut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad context chunk -- possible corruption.
        /// </summary>
        internal static string context_chunk_out_of_range {
            get {
                return ResourceManager.GetString("context_chunk_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid alarm code array length.
        /// </summary>
        internal static string invalid_alarm_code {
            get {
                return ResourceManager.GetString("invalid_alarm_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin needs Little CMS {0}. Current version is {1}..
        /// </summary>
        internal static string invalid_lcms_version {
            get {
                return ResourceManager.GetString("invalid_lcms_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parametric curve type {0}.
        /// </summary>
        internal static string invalid_parametric_curve_type {
            get {
                return ResourceManager.GetString("invalid_parametric_curve_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhitePoint.FromTemp: Invalid temp.
        /// </summary>
        internal static string invalid_whitepoint_from_temp {
            get {
                return ResourceManager.GetString("invalid_whitepoint_from_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUT8 needs 256 entries on prelinearization.
        /// </summary>
        internal static string lut8_invalid_entry_count {
            get {
                return ResourceManager.GetString("lut8_invalid_entry_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUT is not suitable to be saved as LUT16.
        /// </summary>
        internal static string not_suitable_lut16_save {
            get {
                return ResourceManager.GetString("not_suitable_lut16_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUT is not suitable to be saved as LUT8.
        /// </summary>
        internal static string not_suitable_lut8_save {
            get {
                return ResourceManager.GetString("not_suitable_lut8_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut is not suitable to be saved as LutAToB.
        /// </summary>
        internal static string not_suitable_lutatob_save {
            get {
                return ResourceManager.GetString("not_suitable_lutatob_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lut is not suitable to be saved as LutBToA.
        /// </summary>
        internal static string not_suitable_lutbtoa_save {
            get {
                return ResourceManager.GetString("not_suitable_lutbtoa_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLocalizedUnicodeType of len != 12 is not supported..
        /// </summary>
        internal static string not_supported_mlu_length {
            get {
                return ResourceManager.GetString("not_supported_mlu_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multisegment or Inverted parametric curves cannot be written.
        /// </summary>
        internal static string parametric_curve_cannot_write {
            get {
                return ResourceManager.GetString("parametric_curve_cannot_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToneCurve.Smooth: Function Smooth2 failed..
        /// </summary>
        internal static string tonecurve_smooth_failed {
            get {
                return ResourceManager.GetString("tonecurve_smooth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToneCurve.Smooth: Degenerated, mostly poles..
        /// </summary>
        internal static string tonecurve_smooth_mostly_poles {
            get {
                return ResourceManager.GetString("tonecurve_smooth_mostly_poles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToneCurve.Smooth: Degenerated, mostly zeros..
        /// </summary>
        internal static string tonecurve_smooth_mostly_zeros {
            get {
                return ResourceManager.GetString("tonecurve_smooth_mostly_zeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToneCurve.Smooth: Non-Monotonic..
        /// </summary>
        internal static string tonecurve_smooth_non_monotonic {
            get {
                return ResourceManager.GetString("tonecurve_smooth_non_monotonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToneCurve.Smooth: Too many points..
        /// </summary>
        internal static string tonecurve_smooth_too_many_points {
            get {
                return ResourceManager.GetString("tonecurve_smooth_too_many_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create tone curve with zero segments and no table.
        /// </summary>
        internal static string tonecurve_too_few_entries {
            get {
                return ResourceManager.GetString("tonecurve_too_few_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create tone curve of more than 65530 entries.
        /// </summary>
        internal static string tonecurve_too_many_entries {
            get {
                return ResourceManager.GetString("tonecurve_too_many_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many colorants &apos;{0}&apos;.
        /// </summary>
        internal static string too_many_colorants {
            get {
                return ResourceManager.GetString("too_many_colorants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many device coordinates &apos;{0}&apos;.
        /// </summary>
        internal static string too_many_device_coordinates {
            get {
                return ResourceManager.GetString("too_many_device_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many input channels ({0} channels, max={1}).
        /// </summary>
        internal static string too_many_input_channels {
            get {
                return ResourceManager.GetString("too_many_input_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many named colors &apos;{0}&apos;.
        /// </summary>
        internal static string too_many_named_colors {
            get {
                return ResourceManager.GetString("too_many_named_colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown curve type &apos;{0}&apos;.
        /// </summary>
        internal static string unknown_curve_type {
            get {
                return ResourceManager.GetString("unknown_curve_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown record length in dictionary &apos;{0}&apos;.
        /// </summary>
        internal static string unknown_dictionary_record_length {
            get {
                return ResourceManager.GetString("unknown_dictionary_record_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown MPE type &apos;{0}&apos; found..
        /// </summary>
        internal static string unknown_mpe_type {
            get {
                return ResourceManager.GetString("unknown_mpe_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parametric curve type &apos;{0}&apos;.
        /// </summary>
        internal static string unknown_parametric_curve_type {
            get {
                return ResourceManager.GetString("unknown_parametric_curve_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown precision of &apos;{0}&apos;.
        /// </summary>
        internal static string unknown_precision {
            get {
                return ResourceManager.GetString("unknown_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized plugin.
        /// </summary>
        internal static string unrecognized_plugin {
            get {
                return ResourceManager.GetString("unrecognized_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized plugin type {0:X8}.
        /// </summary>
        internal static string unrecognized_plugin_type {
            get {
                return ResourceManager.GetString("unrecognized_plugin_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported interpolation ({0}-&gt;{1} channels).
        /// </summary>
        internal static string unsupported_interpolation {
            get {
                return ResourceManager.GetString("unsupported_interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported parametric curve.
        /// </summary>
        internal static string unsupported_parametric_curve {
            get {
                return ResourceManager.GetString("unsupported_parametric_curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported bit depth for VCGT &apos;{0}&apos;.
        /// </summary>
        internal static string unsupported_vcgt_bit_depth {
            get {
                return ResourceManager.GetString("unsupported_vcgt_bit_depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported number of channels for VCGT &apos;{0}&apos;.
        /// </summary>
        internal static string unsupported_vcgt_channel_count {
            get {
                return ResourceManager.GetString("unsupported_vcgt_channel_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported tag type for VCGT &apos;{0}&apos;.
        /// </summary>
        internal static string unsupported_vcgt_type {
            get {
                return ResourceManager.GetString("unsupported_vcgt_type", resourceCulture);
            }
        }
    }
}
